### ISSUE TITLE
Users need a fluid UX

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/icon-journal#1]
## 💰 Motivation

Users like to use intuitive design! 😄

## 📐 Plan

Create a dynamic wireframe in figma for all features

## 🖼️ Wireframe

https://www.figma.com/file/zzv9CfLYJmBiFYkVLBi4f6/Icon-Journal?node-id=0%3A1

## ✅ Task List

- [x] Plan Welcome / Set-Up page
- [x] Plan Initial Add Journal Page
- [x] Plan View Journal Page
- [x] Set up file structure and link pages (index.html, main.js etx...) 
- [x] Plan Icon styles and color variations 
- [ ] Style Icons in Adobe Illustrator for each feature
