### ISSUE TITLE
Users want to choose their own icons

### ISSUE THREAD

**Issue by keivanmojmali** [keivanmojmali/icon-journal#2]
## 💰 Motivation

Users like inclusive design! 😄

## 📐 Plan

Create initial icon choice walk through

## ✅ Task List

- [ ] Create up welcome page
- [ ] Create multiple identical icon choice pages 
- [ ] Create Data.js to store your icon choices until server is set up
